[package]
name = "hubspot-api"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]

[build-dependencies]
prettyplease = "0.2.22"
progenitor = { git = "https://github.com/oxidecomputer/progenitor" }
serde_json = "1.0"
syn = "2.0"
openapiv3 = "2.1"
serde = { version = "1.0", features = ["derive"] }
config = { version = "0.15.11", default-features = false, features = ["json","serde_json", "toml"] }